name: Docker Build and Push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ gitea.server_url }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # Note: Gitea requires lowercase image names
          tags: |
            ${{ gitea.server_url }}/${{ gitea.repository }}:latest
            ${{ gitea.server_url }}/${{ gitea.repository }}:${{ gitea.sha }}
        env:
          # Fix for older act_runner versions if token parsing fails
          ACTIONS_RUNTIME_TOKEN: ""
