"""add_ai_prompt_templates_table

Revision ID: b45b8f2cd21a
Revises: 20260109_1001_add_ai_config
Create Date: 2026-01-09 20:29:15.129707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45b8f2cd21a'
down_revision: Union[str, None] = '20260109_1001_add_ai_config'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book_tags', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('book_tags', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('tags', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    
    # Seed default templates
    op.execute("""
        INSERT INTO ai_prompt_templates (name, type, template, is_default, description, created_at)
        VALUES
        ('Default Summary', 'summary', E'You are a literary analyst. Generate a concise, informative summary of the following book.\\n\\nBook Title: {book_title}\\nAuthor(s): {authors}\\n\\nExisting Summary:\\n{existing_summary}\\nYou may refine or expand on the existing summary.\\n\\nBook Content ({word_count} words total):\\n{book_content}\\n\\nGenerate a summary that:\\n- Is 150-300 words\\n- Captures the main plot/themes\\n- Mentions key characters or ideas\\n- Avoids spoilers\\n- Is engaging and informative\\n\\nSummary:', true, 'Standard summary prompt', NOW()),
        ('Default Tags', 'tags', E'You are a book cataloging expert. Generate booru-style tags for this book.\\n\\nBook Title: {book_title}\\nAuthor(s): {authors}\\nExisting Metadata Tags: {existing_tags}\\nCurrent Tags: {existing_tags}\\n\\nTag Type Priorities and Limits:\\n{tag_limits}\\n\\nBook Sample:\\n{book_sample}\\n\\nPopular Tags in Library: {popular_tags}\\n\\nGenerate tags following these rules:\\nTAG FORMAT:\\n- Use snake_case format (e.g., "science_fiction")\\n- No spaces, use underscores\\n\\nOUTPUT FORMAT (one per line):\\ntype:tag_name | reason\\n\\nYour tags:', true, 'Standard booru-style tagging', NOW())
        ON CONFLICT (name) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('book_tags', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('book_tags', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    # ### end Alembic commands ###
