"""add_duplicate_handling

Revision ID: fb05402b6d8e
Revises: ef4dde01710a
Create Date: 2026-01-13 21:59:00.303026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb05402b6d8e'
down_revision: Union[str, None] = 'ef4dde01710a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_duplicate', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('books', sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'books', ['duplicate_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tags_usage_count_desc'), 'tags', [sa.literal_column('usage_count DESC')], unique=False)
    op.create_index(op.f('idx_tags_type_usage'), 'tags', ['type', sa.literal_column('usage_count DESC')], unique=False)
    op.create_index(op.f('idx_tags_type_name'), 'tags', ['type', 'name'], unique=False)
    op.create_index(op.f('idx_progress_user_last_read'), 'reading_progress', ['user_id', sa.literal_column('last_read DESC')], unique=False)
    op.create_index(op.f('idx_progress_user_book_unique'), 'reading_progress', ['user_id', 'book_id'], unique=True)
    op.create_index(op.f('idx_progress_is_finished'), 'reading_progress', ['is_finished'], unique=False)
    op.create_index(op.f('idx_collection_books_position'), 'collection_books', ['collection_id', 'position'], unique=False)
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_index(op.f('idx_books_word_count'), 'books', ['word_count'], unique=False)
    op.create_index(op.f('idx_books_series'), 'books', ['series'], unique=False)
    op.create_index(op.f('idx_books_rating'), 'books', ['rating'], unique=False)
    op.create_index(op.f('idx_books_publisher'), 'books', ['publisher'], unique=False)
    op.create_index(op.f('idx_books_language'), 'books', ['language'], unique=False)
    op.create_index(op.f('idx_books_format'), 'books', ['format'], unique=False)
    op.create_index(op.f('idx_books_created_at'), 'books', ['created_at'], unique=False)
    op.drop_column('books', 'duplicate_of_id')
    op.drop_column('books', 'is_duplicate')
    # ### end Alembic commands ###
