"""update cascades for book deletion

Revision ID: 343cca14e0dd
Revises: d7785493f57e
Create Date: 2026-01-14 09:42:13.580555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343cca14e0dd'
down_revision: Union[str, None] = 'd7785493f57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_duplicate_of_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'books', ['duplicate_of_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_duplicate_of_id_fkey'), 'books', 'books', ['duplicate_of_id'], ['id'])
    # ### end Alembic commands ###
