"""add cascade delete for reading progress and bookmarks

Revision ID: d7785493f57e
Revises: fb05402b6d8e
Create Date: 2026-01-14 09:33:00.214320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7785493f57e'
down_revision: Union[str, None] = 'fb05402b6d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookmarks_book_id_fkey'), 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_books_created_at'), table_name='books')
    op.drop_index(op.f('idx_books_format'), table_name='books')
    op.drop_index(op.f('idx_books_language'), table_name='books')
    op.drop_index(op.f('idx_books_publisher'), table_name='books')
    op.drop_index(op.f('idx_books_rating'), table_name='books')
    op.drop_index(op.f('idx_books_series'), table_name='books')
    op.drop_index(op.f('idx_books_word_count'), table_name='books')
    op.drop_index(op.f('idx_collection_books_position'), table_name='collection_books')
    op.drop_index(op.f('idx_progress_is_finished'), table_name='reading_progress')
    op.drop_index(op.f('idx_progress_user_book_unique'), table_name='reading_progress')
    op.drop_index(op.f('idx_progress_user_last_read'), table_name='reading_progress')
    op.drop_constraint(op.f('reading_progress_book_id_fkey'), 'reading_progress', type_='foreignkey')
    op.create_foreign_key(None, 'reading_progress', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_tags_type_name'), table_name='tags')
    op.drop_index(op.f('idx_tags_type_usage'), table_name='tags')
    op.drop_index(op.f('idx_tags_usage_count_desc'), table_name='tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tags_usage_count_desc'), 'tags', [sa.literal_column('usage_count DESC')], unique=False)
    op.create_index(op.f('idx_tags_type_usage'), 'tags', ['type', sa.literal_column('usage_count DESC')], unique=False)
    op.create_index(op.f('idx_tags_type_name'), 'tags', ['type', 'name'], unique=False)
    op.drop_constraint(None, 'reading_progress', type_='foreignkey')
    op.create_foreign_key(op.f('reading_progress_book_id_fkey'), 'reading_progress', 'books', ['book_id'], ['id'])
    op.create_index(op.f('idx_progress_user_last_read'), 'reading_progress', ['user_id', sa.literal_column('last_read DESC')], unique=False)
    op.create_index(op.f('idx_progress_user_book_unique'), 'reading_progress', ['user_id', 'book_id'], unique=True)
    op.create_index(op.f('idx_progress_is_finished'), 'reading_progress', ['is_finished'], unique=False)
    op.create_index(op.f('idx_collection_books_position'), 'collection_books', ['collection_id', 'position'], unique=False)
    op.create_index(op.f('idx_books_word_count'), 'books', ['word_count'], unique=False)
    op.create_index(op.f('idx_books_series'), 'books', ['series'], unique=False)
    op.create_index(op.f('idx_books_rating'), 'books', ['rating'], unique=False)
    op.create_index(op.f('idx_books_publisher'), 'books', ['publisher'], unique=False)
    op.create_index(op.f('idx_books_language'), 'books', ['language'], unique=False)
    op.create_index(op.f('idx_books_format'), 'books', ['format'], unique=False)
    op.create_index(op.f('idx_books_created_at'), 'books', ['created_at'], unique=False)
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key(op.f('bookmarks_book_id_fkey'), 'bookmarks', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
